import type { Metadata } from "next";
import { Inter, Aoboshi_One, Cairo } from 'next/font/google'
// import { GlobalContextProvider } from '@/code/globalContext';
import "../styles/globals.css";
import LayoutContainer from "./layoutContainer";


export const metadata: Metadata = {
  title: "Al-Nafis",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: '--font-inter',
});

const aoboshi = Aoboshi_One({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-aoboshi_one',
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: '--font-cairo',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


      <html lang="en" className={`${inter.variable} ${aoboshi.variable} ${cairo.variable}`}>
        <body className={`bg-onSurface min-h-screen font-inter`}>
          <LayoutContainer>{children}</LayoutContainer>
        </body>
      </html>

  );
}
